### ISSUE TITLE
Button Hover & Disable - Trigger/Colors not working

### ISSUE THREAD

**Issue by hexxone** [DanPristupov/WpfExpressionBlendTheme#15]
Hi there,
I know this is a rather old project but I've taken quite a liking to it.
It even works mostly for .Net 4.5
Though I noticed that for buttons the "hover" and "disabled" colors wont apply.
Do you maybe have a clue how to fix this?

**Comment by DanPristupov** [comment]
> It even works mostly for .Net 4.5

You mean, hover/disabled state doesn't work in .Net > 4.5?

**Comment by hexxone** [comment]
sorry for the delay, somehow I didnt receive a notification about your response.
Yes, thats what I meant :)
