### ISSUE TITLE
When I bind data to ListView, then namespaces are displayed in the listview instead of data

### ISSUE THREAD

**Issue by s34nvideos** [DanPristupov/WpfExpressionBlendTheme#3]
When I bind data to ListView, then namespaces are displayed in the listview instead of actual data. This problem appears when theme is applied, when theme is not used, data re-appears

**Comment by TanyaPristupova** [comment]
Hi s34nvideos. I'm trying to reproduce it, will let you know soon.

**Comment by TanyaPristupova** [comment]
s34nvideos, thank you for your attention to the project.

I didn't notice any problem. If you can, please provide a small example of the code which represents the problem.

There are some possibilities to show data in List view. You can either implement a custom DataTemplate for items or specify DisplayMemberPath.

```
<ListView x:Name="ListView" >
    <ListView.ItemTemplate>
        <DataTemplate>
            <WrapPanel>
                <TextBlock Text="Name: " />
                <TextBlock Text="{Binding DataContext.Name, RelativeSource={RelativeSource TemplatedParent}}" FontWeight="Bold" />
                <TextBlock Text=", " />
                <TextBlock Text="PhoneNumber: " />
                <TextBlock Text="{Binding DataContext.PhoneNumber, RelativeSource={RelativeSource TemplatedParent}}" FontWeight="Bold" />
            </WrapPanel>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
Or

```
<ListView x:Name="ListView1" DisplayMemberPath="Name" />
```
Both of them work properly.

My model class is very simple:
```
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PhoneNumber { get; set; }
    }
```


There is more information about list view binding here:
http://www.wpf-tutorial.com/listview-control/listview-data-binding-item-template/

But if you think there is a bug, please let me know more information how to reproduce it.

**Comment by s34nvideos** [comment]
Thanks for the fast response! Here is what I am working with... As soon as
I try another theme or comment out this theme it works fine. If I use this
theme, it just does a ToString() of my object. It displays the namespace
and class. Hope this helps


XAML
                    <ListView Name="gridYTDResults" ItemsSource="{Binding}">
                        <ListView.View>
                            <GridView>
                                <GridViewColumn Width="200"
Header="Progress">
                                    <GridViewColumn.CellTemplate>
                                        <DataTemplate>
                                            <Grid>
                                                <ProgressBar
Name="progYTDDownloadProgress" Height="20" Value="{Binding Progress}"
HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Minimum="0"
Maximum="100" />
                                                <TextBlock
Name="progYTDDownloadProgressText" HorizontalAlignment="Center"
VerticalAlignment="Center" Text="{Binding ProgressPercent}" />
                                            </Grid>
                                        </DataTemplate>
                                    </GridViewColumn.CellTemplate>
                                </GridViewColumn>
                                <GridViewColumn
DisplayMemberBinding="{Binding VideoTitle}" Header="Video Title"
Width="200" />
                            </GridView>
                        </ListView.View>
                    </ListView>





// list and adding an item to list and setting source
ObservableCollection<DownloadGridItem> list = new
ObservableCollection<DownloadGridItem>();
list.Add(new DownloadGridItem() { VideoTitle = videoTitle, Progress =
progressPercent, UniqueDownloadID = uniqueDownloadID });
gridYTDResults.ItemsSource = list;



Model
    public class DownloadGridItem : INotifyPropertyChanged // Notifies out
ListView automatically when properties change.
    {
        private string uniqueDownloadID;
        private string videoTitle;
        private int progress;
        public event PropertyChangedEventHandler PropertyChanged;

        public string UniqueDownloadID
        {
            get { return uniqueDownloadID; }
            set
            {
                uniqueDownloadID = value;
                OnPropertyChanged("UniqueDownloadID");
            }
        }

        public string VideoTitle
        {
            get { return videoTitle; }
            set
            {
                videoTitle = value;
                OnPropertyChanged("VideoTitle");
            }
        }

        public int Progress
        {
            get { return progress; }
            set
            {
                progress = value;
                OnPropertyChanged("Progress");
                OnPropertyChanged("ProgressPercent");
            }
        }

        public string ProgressPercent
        {
            get { return progress.ToString() + "%"; }
        }

        protected void OnPropertyChanged(string name)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
            {
                handler(this, new PropertyChangedEventArgs(name));
            }
        }
    }

**Comment by TanyaPristupova** [comment]
Thanks. Your code helped me to find a problem in ListView style. There is no quick fix and it will take few hours to make it work. I hope to get it done during the weekend.

**Comment by s34nvideos** [comment]
Thank you for looking into it for me. Just let me know when you get around
to it and ill be happy to test it. Thank you

**Comment by TanyaPristupova** [comment]
There was no style for ListView with a GridView. I added it to the theme. Please pull the latest changes. In order to use it you should set style for list view as following:
```
<ListView Style="{StaticResource ListViewWithGridViewStyle}">
```
Your xaml should look like this:
```
<ListView Name="gridYTDResults" ItemsSource="{Binding}" Style="{StaticResource  ListViewWithGridViewStyle}">
    <ListView.ItemContainerStyle>
        <Style TargetType="{x:Type ListViewItem}" BasedOn="{StaticResource ListViewItemGridViewStyle}">
            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
            <Setter Property="VerticalContentAlignment" Value="Center" />
        </Style>
    </ListView.ItemContainerStyle>
    <ListView.View>
        <GridView ColumnHeaderContainerStyle="{StaticResource GridViewColumnHeaderStyle}">
            <GridViewColumn Width="200" Header="Progress">
                <GridViewColumn.CellTemplate>
                    <DataTemplate>
                        <Grid>
                            <ProgressBar Name="progYTDDownloadProgress" Height="20" Value="{Binding Progress}"
                                         Background="Transparent" BorderBrush="{Binding Foreground, RelativeSource={RelativeSource Self}}" 
                                         Minimum="0" Maximum="100" />
                            <TextBlock Name="progYTDDownloadProgressText" VerticalAlignment="Center"
                                       Text="{Binding ProgressPercent}" Margin="4 0 0 0" />
                        </Grid>
                    </DataTemplate>
                </GridViewColumn.CellTemplate>
            </GridViewColumn>
            <GridViewColumn DisplayMemberBinding="{Binding VideoTitle}" Header="Video Title" Width="200" />
        </GridView>
    </ListView.View>
</ListView>
```

**Comment by s34nvideos** [comment]
great, thank you!

I will make a note that I need to specify a staticresource each I time I
use it, it will probably be something I forget to do everytime :)

Thanks!

**Comment by s34nvideos** [comment]
Hi,

I thought I would mention that these 3 lines are for .NET 4.5 users only.
It kinda threw me off at first because I use 4.0 to target XP. Thanks

            <Trigger Property="IsNewItem" Value="True">
                <Setter Property="Margin" Value="{Binding NewItemMargin,
RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}}"/>
            </Trigger>

**Comment by DanPristupov** [comment]
Hi s34nvideos,

Thanks, I completely missed that. Yes, need to comment that out. Unfortunately there is no way to have same xaml for .Net 4.0 and .Net 4.5. We need to maintain two separate versions of the layout.

P.S. Why do you need to support XP, do you write a software for ATM machines? :)

**Comment by s34nvideos** [comment]
No problem! :) I understand!

It boils down to the fact that my wife is still running XP and I write a
lot of software for our business. She is very stubborn and won't move on! I
don't want to argue with that lol! :)
