### ISSUE TITLE
How can I change this?

### ISSUE THREAD

**Issue by RandomOverflow** [DanPristupov/WpfExpressionBlendTheme#6]
Great theme, I would ask you how can I change the TabItem text Orientation from vertical to horizontal.
https://i.imgur.com/M3rAwFe.png
I only set the property TabStripPlacement of the TabControl to "Left".
Thank you!

**Comment by TanyaPristupova** [comment]
Hi,
You can’t change the text orientation of current tab Item style. I added the “NormalTabItem” style for that. Please pull the latest changes and apply the style to your tab control like shown below:
```
<TabControl TabStripPlacement="Left">
    <TabControl.Resources>
        <Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource NormalTabItem}"/>
    </TabControl.Resources>
    <TabItem Header="TabItem1">
        <TextBlock Text="TabItem1 Content"/>
    </TabItem>
    <TabItem Header="TabItem2">
        <TextBlock Text="TabItem2 Content"/>
    </TabItem>
</TabControl>
```

**Comment by RandomOverflow** [comment]
Added (after updating Styles.xaml)
` <TabControl.Resources>
      <Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource NormalTabItem}"/>
  </TabControl.Resources>`

I have another problem now:
https://i.imgur.com/lKlmWpd.png
The middle column doesn't stretch like before. Did I do something wrong? Thank you.

**Comment by RandomOverflow** [comment]
I fixed changing <Setter Property="HorizontalContentAlignment" Value="Left" /> to <Setter Property="HorizontalContentAlignment" Value="Stretch" /> in the NormalTabItem Style

**Comment by TanyaPristupova** [comment]
Hi,
You are right. There is a  problem with content alignment. Thank you for fixing that. I will apply your changes to the source code.
