### ISSUE TITLE
Context menu's disabled options foregroundColor appear as enabled

### ISSUE THREAD

**Issue by LazaroOnline** [DanPristupov/WpfExpressionBlendTheme#8]
The context menu option's foreground color makes the option look enabled when it is actually disabled.

For example this "copy" text command should be disabled since there is no text selected.
Hovering the mouse or clicking makes nothing.
The foreground should be gray instead of white.

![command disabled context menu bug looks enabled](https://cloud.githubusercontent.com/assets/13026853/22187605/ce6e6846-e109-11e6-8e60-519ee0ad91e3.png)
```xaml
<RichTextBox.ContextMenu>
	<ContextMenu>
		<MenuItem Command="Copy" Style="{StaticResource MenuCopy}" />
	</ContextMenu>
</RichTextBox.ContextMenu>

**Comment by TanyaPristupova** [comment]
Hi LazaroOnline,
The disabled menu looks good in Dark Blend Theme example.
<img width="290" alt="2017-02-14 at 09 40" src="https://cloud.githubusercontent.com/assets/9998405/22922046/5bce442e-f29c-11e6-8494-583459988064.png">
Please ensure that your MenuCopy style doesn’t override the disabled foreground. 

Regards,
Tanya

**Comment by LazaroOnline** [comment]
Hello, thanks a lot for the reply, you are right, it was another style that was overriding it.
The theme is alright!
